---
title: "05_LongBranch_removal"
output: html_document
---

```{r}

library(Biostrings)
library(openxlsx)
library(seqinr) # read.fasta
library(phytools) # for midpoint.root
```

```{r}
# Example: remove sequences named "seq1" and "seq3"
remove_names <- c("UPH47978.1", "AAO82557.1", "SQE55453.1", "QJS18567.1", "WP_371830858.1", "WP_076758937.1", "WP_151698803.1", "WP_014824101.1")
fasta <- readAAStringSet("Data/05_LongBranch_removal/3di_unaligned_with_longbranches.fasta")
xlsfn = "Data/RenamingSequences.xlsx"
xls = openxlsx::read.xlsx(xlsxFile=xlsfn, sheet=1, startRow=1, colNames=TRUE)
accession_number = xls$AccessionNumber
protein_name = fixnames(xls$protein)
for (i in 1:length(remove_names))
		{
		TF = grepl(pattern=remove_names[i], x=accession_number)
		tipnum = ((1:length(TF))[TF])
		remove_names[i] = protein_name[tipnum]

		} # END for (i in 1:length(remove_names))
	

remove_names
# Filter out unwanted sequences
filtered_fasta <- fasta[!(names(fasta) %in% remove_names)]
length(filtered_fasta)
writeXStringSet(filtered_fasta, "Data/05_LongBranch_removal/3di_unaligned.fasta")
```

```{r}
# Example: remove sequences named "seq1" and "seq3"
remove_names <- c("UPH47978.1", "AAO82557.1", "SQE55453.1", "QJS18567.1", "WP_371830858.1", "WP_076758937.1", "WP_151698803.1", "WP_014824101.1")
fasta <- readAAStringSet("Data/05_LongBranch_removal/aa_unaligned_with_longbranches.fasta")
xlsfn = "Data/RenamingSequences.xlsx"
xls = openxlsx::read.xlsx(xlsxFile=xlsfn, sheet=1, startRow=1, colNames=TRUE)
accession_number = xls$AccessionNumber
protein_name = fixnames(xls$protein)
for (i in 1:length(remove_names))
		{
		TF = grepl(pattern=remove_names[i], x=accession_number)
		tipnum = ((1:length(TF))[TF])
		remove_names[i] = protein_name[tipnum]

		} # END for (i in 1:length(remove_names))
	

remove_names
# Filter out unwanted sequences
filtered_fasta <- fasta[!(names(fasta) %in% remove_names)]
length(filtered_fasta)
writeXStringSet(filtered_fasta, "Data/05_LongBranch_removal/aa_unaligned.fasta")
```

## Alignment and other steps
# Align the 3di sequences, using famsa3di
```{bash}

famsa3di ./Data/05_LongBranch_removal/3di_unaligned.fasta ./Data/05_LongBranch_removal/3di_famsa3dialigned.fasta

```

# Align the AAs to the famsa3di alignment
```{r}
source("~/GitHub/str2phy/Rsrc/str2phy_v1.R")

aligned_fn = "Data/05_LongBranch_removal/3di_famsa3diAligned.fasta"
unaligned_fn = "Data/05_LongBranch_removal/aa_unaligned.fasta"
outfn = "Data/05_LongBranch_removal/aa_famsa3diAligned.fasta"
aligned_AAs = align_3dis_to_AAs(aligned_fn, unaligned_fn, outfn)
moref(outfn)
```

# Trim the alignments to just columns with >35% complete data
```{bash}

trimal -in ./Data/05_LongBranch_removal/aa_famsa3diAligned.fasta -out ./Data/05_LongBranch_removal/aa_famsa3diAligned_trim35.fasta -gt 0.35 -colnumbering | tee ./Data/05_LongBranch_removal/aa_famsa3diAligned_trim35_cols.txt

trimal -in ./Data/05_LongBranch_removal/3di_famsa3diAligned.fasta -out ./Data/05_LongBranch_removal/3di_famsa3diAligned_trim35.fasta -gt 0.35 -colnumbering | tee ./Data/05_LongBranch_removal/3di_famsa3diAligned_trim35_cols.txt

```

# Horizontally concatenate 2 alignment files
```{r}

fn1 = "Data/05_LongBranch_removal/aa_famsa3diAligned_trim35.fasta"
fn2 = "Data/05_LongBranch_removal/aa_famsa3diAligned_trim35.fasta"
fn3 = "Data/05_LongBranch_removal/aa_3di_famsa3diAligned_trim35.fasta"
fn3
merged_df = hcat_align_fns(fn1, fn2, fn3)
merged_df
```

## Reordering_ALignment
```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/3di_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/3di_nj/input.fa.final_tree.used_alg.fa") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/3di_nj/input.fa.final_tree.used_alg_reordered.fa") ## out file  - renamed, reordered fasta file
```

```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/3di_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/3di_nj/3di_famsa3dialigned.fasta") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/3di_nj/3di_famsa3dialigned_reordered.fasta") ## out file  - renamed, reordered fasta
```

```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/3di_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/3di_nj/aa_famsa3dialigned.fasta") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/3di_nj/aa_famsa3dialigned_reordered.fasta") ## out file  - renamed, reordered fasta
```

```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/aa_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/aa_nj/input.fa.final_tree.used_alg.fa") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/aa_nj/input.fa.final_tree.used_alg_reordered.fa") ## out file  - renamed, reordered fasta file
```

```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/aa_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/aa_nj/aa_famsa3dialigned.fasta") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/aa_nj/aa_famsa3dialigned_reordered.fasta") ## out file  - renamed, reordered fasta
```


```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/3di_aa_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/3di_aa_nj/input.fa.final_tree.used_alg.fa") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/3di_aa_nj/input.fa.final_tree.used_alg_reordered.fa") ## out file  - renamed, reordered fasta file
```

```{r}
tr_renamed <- ape::read.tree("Data/05_LongBranch_removal/3di_aa_nj/outTree_unrooted.nwk") ## renamed tree file
plotTree(tr_renamed)
desired_order <- tr_renamed$tip.label[order((get("last_plot.phylo", envir = .PlotPhyloEnv)$yy[1:Ntip(tr_renamed)]))]
fasta_file <- read.fasta (file = "Data/05_LongBranch_removal/3di_aa_nj/merged.fasta") ## renamed fasta file
fasta_ids <-names(fasta_file)
tip_ids <- desired_order
reordered_fasta <- fasta_file[(match(tip_ids, fasta_ids))]
write.fasta(sequences = reordered_fasta, names=desired_order, file.out = "Data/05_LongBranch_removal/3di_aa_nj/merged_reordered.fasta") ## out file  - renamed, reordered fasta
```

```{r}
library(bio3d)
pdb <- read.pdb("Data/Structures/Alphafold/Alphafold_FliF.pdb")
seq <- pdbseq(pdb)
seqinr::write.fasta(sequences = list(seq), names = "FliF", file.out = "Data/Structures/Alphafold/Alphafold_FliF.fasta")

pdb <- read.pdb("Data/Structures/Alphafold/Alphafold_SpoIIIAG.pdb")
seq <- pdbseq(pdb)
seqinr::write.fasta(sequences = list(seq), names = "FliF", file.out = "Data/Structures/Alphafold/Alphafold_SpoIIIAG.fasta")

pdb <- read.pdb("Data/Structures/Alphafold/Alphafold_SpoIIIAH.pdb")
seq <- pdbseq(pdb)
seqinr::write.fasta(sequences = list(seq), names = "FliF", file.out = "Data/Structures/Alphafold/Alphafold_SpoIIIAH.fasta")

```

